# Generated by Django 4.1.7 on 2023-03-09 09:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60, verbose_name='Город')),
                ('street', models.CharField(max_length=60, verbose_name='Улица')),
                ('house', models.CharField(max_length=30, verbose_name='Дом')),
                ('connection_date', models.DateField(blank=True, null=True, verbose_name='Дата подключения')),
                ('blackout_date', models.DateField(blank=True, null=True, verbose_name='Дата отключения')),
            ],
            options={
                'verbose_name': 'Адрес подключения',
                'verbose_name_plural': 'Адреса подключения',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('conclusion_date', models.DateField(blank=True, null=True, verbose_name='Дата заключения')),
                ('address', models.ManyToManyField(to='contracts.address')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
    ]
